### ISSUE TITLE
opcode events

### ISSUE THREAD

**Issue by ejrgilbert** [ejrgilbert/whamm#132]
Things to go back and do (things that will be complex and can be done on a second pass):
- [x] `br`/`block`/`loop`/`if`/`else`: `wasm:opcode:br:after`: It semantically makes sense for the body to be emitted at the start of the target `br` relative depth. This will need to be configurable with predicates, e.g. `wasm:opcode:br:after / imm == 0/` would only emit the body into the `br`s with relative depth 0 AND into that block! This would be similar to the idea of `after` for a block! see [orca#132](https://github.com/thesuhas/orca/issues/132)
- [x] `unreachable`: Only enable using `alt` and `before` for `unreachable` opcodes since `after` wouldn't be executable. Figure out how to test `before` since hitting `unreachable` keeps us from making assertions as normal...
- [x] `block`/`loop`/`if`/`try`: These opcodes have a `BlockType` as the immediate, it would be cool to support reading/manipulating via some struct interaction syntax. See #139 
- [x] `block`/`loop`/`if`/`else`: start/end?
- [x] `block`/`loop`/`if`/`else`: disable using `alt`
- [x] `u32` handling, see [orca#133](https://github.com/thesuhas/orca/issues/133)

**Comment by ejrgilbert** [comment]
PR #140
